### ISSUE TITLE
Validation Error on newer Jest

### ISSUE THREAD

**Issue by eldyvoon** [justinsisley/Jest-CSS-Modules#13]
```
Validation Error:

  Option "transform" must be of type:
    object
  but instead received:
    string

```

It seems like Jest has updated something. I can't use this in package.json anymore
```

{
  "jest": {
    "scriptPreprocessor": "<rootDir>/node_modules/jest-css-modules",
  }
}
```

**Comment by trevorlinan** [comment]
I was getting errors as well that "scriptPreprocessor" was no longer used and to use "transform" instead. However, setting the modules directory in "transform" didn't work. The newest readme.md on the official Github page shows to use the "moduleNameMapper" instead. I updated my package.json with this configuration and it worked. I hope this helps.

{
    "jest": {
        "transform": {
          ".*": "<rootDir>/node_modules/babel-jest"
        },
        "moduleNameMapper": {
          "\\.(scss)$": "<rootDir>/node_modules/jest-css-modules"
        }
      },
}

**Comment by trevorlinan** [comment]
I was getting errors as well that "scriptPreprocessor" was no longer used and to use "transform" instead. However, setting the modules directory in "transform" didn't work. The newest readme.md on the official Github page shows to use the "moduleNameMapper" instead. I updated my package.json with this configuration and it worked. I hope this helps.

```
{
    "jest": {
        "transform": {
          ".*": "<rootDir>/node_modules/babel-jest"
        },
        "moduleNameMapper": {
          "\\.(scss)$": "<rootDir>/node_modules/jest-css-modules"
        }
      },
}
```

**Comment by Fensterbank** [comment]
Thanks for this example, unfortunately this doesn't work for my project.
In the js component files my scss imports works like this:
`import styles from './TagSection.scss';`

When I use the configuration you provided, variable `styles` is an `object { process: [Function: process] }`.
It is better than before (where it has been just a `string "TagSection.scss"`), but it's still not correct.

Any other idea?

**Comment by loopmode** [comment]
For me, the solution by @Fensterbank almos worked.
intead of
`'^.+\\.(js|jsx)$': '<rootDir>/node_modules/babel-jest'`
I had to do
`'^.+\\.(js|jsx)$': 'babel-jest'`

**Comment by justinsisley** [comment]
I'm going to close this, as I believe this problem is better solved by the [identity-obj-proxy](https://github.com/keyz/identity-obj-proxy) project, which has it's usage documented in the same link provided above: https://jestjs.io/docs/en/webpack.html#mocking-css-modules.

In version 2.0 of this project, I'll just be handing off all work to `identity-obj-proxy` so existing users of this library aren't negatively affected.
